export const T = Object.freeze({
  VOID: 0,
  GRASS: 1,
  GRASS_D: 2,
  TALL: 3,
  PATH: 4,
  STONE: 5,
  DIRT: 6,
  WATER: 7,
  WATER_D: 8,
  SAND: 9,
  WOOD: 10,
  RUG: 11,
  FLAG: 12,
  ASH: 13,
  MOSS: 14,
  FLOWER: 15,
  HEARTH: 16,
  DOCK: 17,
  SHRINE: 18,
  LEAVES: 19,
  ROAD: 20,
  NEON: 21,
  FENCE: 22,
  CONCRETE: 23,
});

export const TILE_WALK = {
  [T.VOID]: false,
  [T.GRASS]: true,
  [T.GRASS_D]: true,
  [T.TALL]: true,
  [T.PATH]: true,
  [T.STONE]: true,
  [T.DIRT]: true,
  [T.WATER]: false,
  [T.WATER_D]: false,
  [T.SAND]: true,
  [T.WOOD]: true,
  [T.RUG]: true,
  [T.FLAG]: true,
  [T.ASH]: true,
  [T.MOSS]: true,
  [T.FLOWER]: true,
  [T.HEARTH]: true,
  [T.DOCK]: true,
  [T.SHRINE]: true,
  [T.LEAVES]: true,
  [T.ROAD]: true,
  [T.NEON]: true,
  [T.FENCE]: false,
  [T.CONCRETE]: true,
};

export const TILE_NAME = {
  [T.GRASS]: 'grass',
  [T.GRASS_D]: 'deep grass',
  [T.TALL]: 'tall grass',
  [T.PATH]: 'worn path',
  [T.STONE]: 'flagstones',
  [T.DIRT]: 'dirt',
  [T.WATER]: 'dark water',
  [T.WATER_D]: 'deep water',
  [T.SAND]: 'silt',
  [T.WOOD]: 'hearth boards',
  [T.RUG]: 'woven rug',
  [T.FLAG]: 'plaza stone',
  [T.ASH]: 'ash',
  [T.MOSS]: 'moss',
  [T.FLOWER]: 'moonflowers',
  [T.HEARTH]: 'the hearth',
  [T.DOCK]: 'dock boards',
  [T.SHRINE]: 'binding shrine',
  [T.LEAVES]: 'leaf litter',
  [T.ROAD]: 'stone road',
  [T.NEON]: 'sigil plaza',
  [T.FENCE]: 'weathered fence',
  [T.CONCRETE]: 'parking lot',
};
